name: Compile

on:
  push:
    branches:
      - 'master'
      - 'release-'
    tags:
      - '*'
  pull_request:

jobs:
  compile:
    name: juliac - Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.12'
          - '~1.13.0-0'
        os:
          - ubuntu-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v3
      - name: Compile Runic with juliac
        run: |
          make -C juliac
      - name: Smoke test compiled binary
        run: |
          ./juliac/runicc --check --diff .
